# collect_data.py - Collect sample URLs for tracking detection model training

import requests
import pandas as pd

# Expanded manually curated URL lists (100 each)

tracker_free_urls = [
    "https://www.wikipedia.org/",
    "https://www.gnu.org/",
    "https://www.mozilla.org/",
    "https://www.signal.org/",
    "https://www.duckduckgo.com/",
    "https://www.nationalgeographic.com/",
    "https://www.w3schools.com/",
    "https://www.example.com/",
    "https://www.bbc.com/",
    "https://www.cit.ac.in/",
    "https://www.noaa.gov/",
    "https://www.khanacademy.org/",
    "https://www.archlinux.org/",
    "https://www.python.org/",
    "https://www.raspberrypi.org/",
    "https://www.stackoverflow.com/",
    "https://www.linuxfoundation.org/",
    "https://www.debian.org/",
    "https://www.gnu.org/software/bash/",
    "https://www.apache.org/",
    "https://www.eclipse.org/",
    "https://www.vim.org/",
    "https://www.postgresql.org/",
    "https://www.libreoffice.org/",
    "https://www.blender.org/",
    "https://www.gimp.org/",
    "https://www.freedesktop.org/",
    "https://www.fsf.org/",
    "https://www.torproject.org/",
    "https://www.openstreetmap.org/",
    "https://www.ccc.de/",
    "https://www.letsencrypt.org/",
    "https://www.ietf.org/",
    "https://www.w3.org/",
    "https://www.iso.org/",
    "https://www.eclipse.org/",
    "https://www.mit.edu/",
    "https://www.harvard.edu/",
    "https://www.stanford.edu/",
    "https://www.caltech.edu/",
    "https://www.berkeley.edu/",
    "https://www.nasa.gov/",
    "https://www.esa.int/",
    "https://www.fsf.org/",
    "https://www.apache.org/",
    "https://www.mysql.com/",
    "https://www.git-scm.com/",
    "https://www.djangoproject.com/",
    "https://www.flask.palletsprojects.com/",
    "https://www.tutorialspoint.com/",
    "https://www.geeksforgeeks.org/",
    "https://www.javatpoint.com/",
    "https://www.w3resource.com/",
    "https://www.php.net/",
    "https://www.ruby-lang.org/",
    "https://www.scala-lang.org/",
    "https://www.perl.org/",
    "https://www.postman.com/",
    "https://www.getbootstrap.com/",
    "https://www.jquery.com/",
    "https://www.reactjs.org/",
    "https://www.angular.io/",
    "https://www.vuejs.org/",
    "https://www.djangoproject.com/",
    "https://www.tensorflow.org/",
    "https://www.pytorch.org/",
    "https://www.scipy.org/",
    "https://www.numpy.org/",
    "https://www.matplotlib.org/",
    "https://www.djangoproject.com/",
    "https://www.jenkins.io/",
    "https://www.circleci.com/",
    "https://www.travis-ci.com/",
    "https://www.github.com/",
    "https://www.gitlab.com/",
    "https://www.bitbucket.org/",
    "https://www.digitalocean.com/",
    "https://www.linode.com/",
    "https://www.heroku.com/",
    "https://www.netlify.com/",
    "https://www.vercel.com/",
    "https://www.cloudflare.com/",
    "https://www.duckduckgo.com/",
    "https://www.ecosia.org/",
    "https://www.startpage.com/",
    "https://www.qwant.com/",
    "https://www.protonmail.com/",
    "https://www.tutanota.com/",
    "https://www.fastmail.com/",
    "https://www.zoho.com/",
    "https://www.nextcloud.com/",
    "https://www.syncthing.net/"
]

tracker_heavy_urls = [
    "https://www.cnn.com/",
    "https://www.nytimes.com/",
    "https://www.india.com/",
    "https://www.amazon.com/",
    "https://www.facebook.com/",
    "https://www.timesofindia.indiatimes.com/",
    "https://www.yahoo.com/",
    "https://www.forbes.com/",
    "https://www.cricbuzz.com/",
    "https://www.theverge.com/",
    "https://www.reddit.com/",
    "https://www.instagram.com/",
    "https://www.tiktok.com/",
    "https://www.snapchat.com/",
    "https://www.linkedin.com/",
    "https://www.ebay.com/",
    "https://www.netflix.com/",
    "https://www.hulu.com/",
    "https://www.hotstar.com/",
    "https://www.espn.com/",
    "https://www.cnbc.com/",
    "https://www.msn.com/",
    "https://www.weather.com/",
    "https://www.booking.com/",
    "https://www.expedia.com/",
    "https://www.tripadvisor.com/",
    "https://www.airbnb.com/",
    "https://www.tinder.com/",
    "https://www.bumble.com/",
    "https://www.quora.com/",
    "https://www.medium.com/",
    "https://www.buzzfeed.com/",
    "https://www.pinterest.com/",
    "https://www.spotify.com/",
    "https://www.soundcloud.com/",
    "https://www.apple.com/",
    "https://www.microsoft.com/",
    "https://www.samsung.com/",
    "https://www.hp.com/",
    "https://www.dell.com/",
    "https://www.lenovo.com/",
    "https://www.asus.com/",
    "https://www.nike.com/",
    "https://www.adidas.com/",
    "https://www.zara.com/",
    "https://www.hm.com/",
    "https://www.flipkart.com/",
    "https://www.paytm.com/",
    "https://www.snapdeal.com/",
    "https://www.alibaba.com/",
    "https://www.myntra.com/",
    "https://www.naukri.com/",
    "https://www.monster.com/",
    "https://www.glassdoor.com/",
    "https://www.indeed.com/",
    "https://www.timesjobs.com/",
    "https://www.shiksha.com/",
    "https://www.udemy.com/",
    "https://www.coursera.org/",
    "https://www.edx.org/",
    "https://www.udacity.com/",
    "https://www.codecademy.com/",
    "https://www.skillshare.com/",
    "https://www.datacamp.com/",
    "https://www.linkedin.com/learning/",
    "https://www.pluralsight.com/",
    "https://www.hackerrank.com/",
    "https://www.codechef.com/",
    "https://www.leetcode.com/",
    "https://www.topcoder.com/",
    "https://www.kaggle.com/",
    "https://www.geeksforgeeks.org/",
    "https://www.javatpoint.com/",
    "https://www.w3schools.com/"
]

def save_urls():
    tracker_free = [{"url": url, "label": 0} for url in tracker_free_urls]
    tracker_heavy = [{"url": url, "label": 1} for url in tracker_heavy_urls]

    all_data = tracker_free + tracker_heavy

    df = pd.DataFrame(all_data)
    print(df.head())
    df.to_csv("/home/anish/Privacy checker extension/data/urls.csv", index=False)
    print("Saved URLs to data\\urls.csv")

if __name__ == "__main__":
    save_urls()
